# Medicine Recommendation System

In [4]:
#import Necessary  Library 


import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

#Import Models 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix

#### Load Dataset

In [6]:
dataset = pd.read_csv('Training.csv')

In [7]:
dataset

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [8]:
dataset.shape

(4920, 133)

In [9]:
dataset.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [10]:
dataset.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [11]:
dataset.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [12]:
dataset["prognosis"].value_counts()

prognosis
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
All

In [13]:
len(dataset["prognosis"].value_counts())

41

In [14]:
dataset["prognosis"].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [15]:
X = dataset.drop("prognosis" , axis = 1)
y = dataset["prognosis"]

In [17]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [18]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [19]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [20]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3, random_state=42)

In [22]:
X_train

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
682         0          0                     0                    0   
3963        0          0                     0                    0   
3126        0          0                     0                    0   
4480        0          0                     0                    0   
3411        0          0                     0                    0   
...       ...        ...                   ...                  ...   
4426        0          1                     0                    0   
466         0          0                     0                    0   
3092        0          1                     0                    0   
3772        1          1                     1                    0   
860         1          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
682           0       1           0             0        0                 0   
3963          0       1           0             0        0                 0   
3126          0       0           0             0        0                 0   
4480          0       0           0             0        1                 0   
3411          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4426          0       0           1             0        0                 0   
466           0       0           0             0        0                 0   
3092          0       1           1             0        0                 0   
3772          0       0           0             0        0                 0   
860           0       0           0             1        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
682   ...                   0           0         0             0   
3963  ...                   0           0         0             0   
3126  ...                   0           0         0             0   
4480  ...                   0           0         0             0   
3411  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4426  ...                   0           0         0             1   
466   ...                   0           0         0             0   
3092  ...                   0           0         0             0   
3772  ...                   0           0         0             0   
860   ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
682                     0                     0                   0        0   
3963                    0                     0                   0        0   
3126                    0                     0                   0        0   
4480                    0                     0                   0        0   
3411                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4426                    1                     1                   1        0   
466                     0                     0                   0        0   
3092                    0                     0                   0        0   
3772                    0                     0                   0        0   
860                     0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
682                      0                  0  
3963                     0                  0  
3126                     0                  0  
4480                     0                  0  
3411                     0                  0  
...                    ...                ...  
4426                     0                  0  
466               

In [23]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
373         0          1                     0                    0   
4916        0          1                     0                    0   
1550        0          0                     0                    0   
3081        0          0                     0                    0   
3857        1          0                     0                    0   
...       ...        ...                   ...                  ...   
3649        1          1                     1                    0   
1694        0          0                     0                    0   
4767        0          0                     0                    0   
3721        0          0                     0                    0   
2222        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
373           0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
1550          0       0           0             0        0                 0   
3081          0       0           0             0        0                 0   
3857          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
3649          0       0           0             0        0                 0   
1694          0       0           0             0        0                 0   
4767          0       0           0             0        1                 0   
3721          0       0           0             0        0                 0   
2222          0       1           1             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
373   ...                   0           1         1             0   
4916  ...                   1           1         1             0   
1550  ...                   0           0         0             0   
3081  ...                   0           0         0             0   
3857  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
3649  ...                   0           0         0             0   
1694  ...                   0           0         0             0   
4767  ...                   0           0         0             0   
3721  ...                   0           0         0             0   
2222  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
373                     0                     0                   0        0   
4916                    0                     0                   0        0   
1550                    0                     0                   0        0   
3081                    0                     0                   0        0   
3857                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
3649                    0                     0                   0        0   
1694                    0                     0                   0        0   
4767                    0                     0                   0        0   
3721                    0                     0                   0        0   
2222                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
373                      0                  0  
4916                     0                  0  
1550                     0                  0  
3081                     0                  0  
3857                     0                  0  
...                    ...                ...  
3649                     0                  0  
1694              

In [33]:
y_train

array([34, 34, 23, ..., 11, 15, 14])

In [34]:
len(y_train)

3444

In [35]:
y_test

array([ 2,  2, 24, ..., 30, 26, 11])

In [36]:
len(y_test)

1476

In [65]:
model1="Random Forest"
rf = RandomForestClassifier(n_estimators= 100 , random_state=42)
rf.fit(X_train , y_train)
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test , y_pred)
cm = confusion_matrix(y_test , y_pred)
accuracy*100
print(f"{model1} Accuracy Score is {accuracy * 100:.2f}%")
print(f"{model1} Confusion_matrix : \n{cm}")

Random Forest Accuracy Score is 100.00%
Random Forest Confusion_matrix : 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [66]:
model2="Support Vector Classifier"
svc = SVC(kernel = 'linear')
svc = SVC(kernel = 'linear')
svc.fit(X_train , y_train)
y_pred = svc.predict(X_test)
cm = confusion_matrix(y_test , y_pred)
accuracy*100
print(f"{model2} Accuracy Score is {accuracy * 100:.2f}%")
print(f"{model2} Confusion_matrix : \n{cm}")

Support Vector Classifier Accuracy Score is 100.00%
Support Vector Classifier Confusion_matrix : 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [67]:
model3="Gradient Boosting"
gb=GradientBoostingClassifier(n_estimators=100 , random_state = 42)
gb.fit(X_train , y_train)
cm = confusion_matrix(y_test , y_pred)
accuracy*100
print(f"{model3} Accuracy Score is {accuracy * 100:.2f}%")
print(f"{model3} Confusion_matrix : \n{cm}")


Gradient Boosting Accuracy Score is 100.00%
Gradient Boosting Confusion_matrix : 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [68]:
model4= "K-Nearest Neighbors"
kn=KNeighborsClassifier(n_neighbors= 5)
kn.fit(X_train , y_train)
y_pred = kn.predict(X_test)
accuracy = accuracy_score(y_test , y_pred)
cm = confusion_matrix(y_test , y_pred)
accuracy*100
print(f"{model4} Accuracy Score is {accuracy * 100:.2f}%")
print(f"{model4} Confusion_matrix : \n{cm}")

K-Nearest Neighbors Accuracy Score is 100.00%
K-Nearest Neighbors Confusion_matrix : 
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [77]:
import pickle

# Save the Random Forest (RF) model
pickle.dump(rf , open("rf.pkl","wb"))

# Save the Support Vector Classifier (SVC) model
pickle.dump(svc , open("svc.pkl","wb"))

print("Models saved successfully!")

Models saved successfully!


In [78]:
#load model 

rf = pickle.load(open("rf.pkl","rb"))
svc = pickle.load(open("svc.pkl","rb"))

In [85]:
# test 1 

test_1=X_test.iloc[1].values.reshape(1,-1)
test_1

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [86]:
rf.predict(test_1)

array([2])

In [87]:
svc.predict(test_1)

array([2])

In [89]:
# test 2 

test_2=X_test.iloc[7].values.reshape(1,-1)
test_2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [90]:
rf.predict(test_2)

array([5])

In [91]:
svc.predict(test_2)

array([5])

### Recommendation and Prediction

In [92]:
#load few data sets

precaution = pd.read_csv("precautions_df.csv")
workout = pd.read_csv("workout_df.csv")
medication = pd.read_csv("medications.csv")
diets = pd.read_csv("diets.csv")
description = pd.read_csv("description.csv")

In [93]:
precaution

Unnamed: 0                                  Disease  \
0            0                            Drug Reaction   
1            1                                  Malaria   
2            2                                  Allergy   
3            3                           Hypothyroidism   
4            4                                Psoriasis   
5            5                                     GERD   
6            6                      Chronic cholestasis   
7            7                              hepatitis A   
8            8                          Osteoarthristis   
9            9  (vertigo) Paroymsal  Positional Vertigo   
10          10                             Hypoglycemia   
11          11                                     Acne   
12          12                                Diabetes    
13          13                                 Impetigo   
14          14                            Hypertension    
15          15                      Peptic ulcer diseae   
16          16             Dimorphic hemmorhoids(piles)   
17          17                              Common Cold   
18          18                              Chicken pox   
19          19                     Cervical spondylosis   
20          20                          Hyperthyroidism   
21          21                  Urinary tract infection   
22          22                           Varicose veins   
23          23                                     AIDS   
24          24             Paralysis (brain hemorrhage)   
25          25                                  Typhoid   
26          26                              Hepatitis B   
27          27                         Fungal infection   
28          28                              Hepatitis C   
29          29                                 Migraine   
30          30                         Bronchial Asthma   
31          31                      Alcoholic hepatitis   
32          32                                 Jaundice   
33          33                              Hepatitis E   
34          34                                   Dengue   
35          35                              Hepatitis D   
36          36                             Heart attack   
37          37                                Pneumonia   
38          38                                Arthritis   
39          39                          Gastroenteritis   
40          40                             Tuberculosis   

                            Precaution_1                        Precaution_2  \
0                        stop irritation            consult nearest hospital   
1               Consult nearest hospital                     avoid oily food   
2                         apply calamine             cover area with bandage   
3                          reduce stress                            exercise   
4       wash hands with warm soapy water        stop bleeding using pressure   
5                 avoid fatty spicy food       avoid lying down after eating   
6                             cold baths                  anti itch medicine   
7               Consult nearest hospital                  wash hands through   
8                          acetaminophen            consult nearest hospital   
9                               lie down         avoid sudden change in body   
10                      lie down on side                      check in pulse   
11                            bath twice              avoid fatty spicy food   
12                    have balanced diet                            exercise   
13      soak affected area in warm water                     use antibiotics   
14                            meditation                          salt baths   
15                avoid fatty spicy food              consume probiotic food   
16                avoid fatty spicy food                 consume witch hazel   
17           drink vitamin c rich drinks                         take vapour   
18   

In [94]:
workout

Unnamed: 0.1  Unnamed: 0           disease  \
0               0           0  Fungal infection   
1               1           1  Fungal infection   
2               2           2  Fungal infection   
3               3           3  Fungal infection   
4               4           4  Fungal infection   
..            ...         ...               ...   
405           405         405          Impetigo   
406           406         406          Impetigo   
407           407         407          Impetigo   
408           408         408          Impetigo   
409           409         409          Impetigo   

                               workout  
0                   Avoid sugary foods  
1                   Consume probiotics  
2            Increase intake of garlic  
3               Include yogurt in diet  
4                Limit processed foods  
..                                 ...  
405  Consult a healthcare professional  
406     Follow medical recommendations  
407                   Avoid scratching  
408        Take prescribed antibiotics  
409                Practice wound care  

[410 rows x 4 columns]

In [95]:
medication

Disease  \
0                         Fungal infection   
1                                  Allergy   
2                                     GERD   
3                      Chronic cholestasis   
4                            Drug Reaction   
5                     Peptic ulcer disease   
6                                     AIDS   
7                                 Diabetes   
8                          Gastroenteritis   
9                         Bronchial Asthma   
10                            Hypertension   
11                                Migraine   
12                    Cervical spondylosis   
13            Paralysis (brain hemorrhage)   
14                                Jaundice   
15                                 Malaria   
16                             Chicken pox   
17                                  Dengue   
18                                 Typhoid   
19                             hepatitis A   
20                             Hepatitis B   
21                             Hepatitis C   
22                             Hepatitis D   
23                             Hepatitis E   
24                     Alcoholic hepatitis   
25                            Tuberculosis   
26                             Common Cold   
27                               Pneumonia   
28            Dimorphic hemmorhoids(piles)   
29                            Heart attack   
30                          Varicose veins   
31                          Hypothyroidism   
32                         Hyperthyroidism   
33                            Hypoglycemia   
34                         Osteoarthristis   
35                               Arthritis   
36  (vertigo) Paroymsal Positional Vertigo   
37                                    Acne   
38                 Urinary tract infection   
39                               Psoriasis   
40                                Impetigo   

                                           Medication  
0   ['Antifungal Cream', 'Fluconazole', 'Terbinafi...  
1   ['Antihistamines', 'Decongestants', 'Epinephri...  
2   ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...  
3   ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...  
4   ['Antihistamines', 'Epinephrine', 'Corticoster...  
5   ['Antibiotics', 'Proton Pump Inhibitors (PPIs)...  
6   ['Antiretroviral drugs', 'Protease inhibitors'...  
7   ['Insulin', 'Metformin', 'Sulfonylureas', 'DPP...  
8   ['Antibiotics', 'Antiemetic drugs', 'Antidiarr...  
9   ['Bronchodilators', 'Inhaled corticosteroids',...  
10  ['Antihypertensive medications', 'Diuretics', ...  
11  ['Analgesics', 'Triptans', 'Ergotamine derivat...  
12  ['Pain relievers', 'Muscle relaxants', 'Physic...  
13  ['Blood thinners', 'Clot-dissolving medication...  
14  ['IV fluids', 'Blood transfusions', 'Liver tra...  
15  ['Antimalarial drugs', 'Antipyretics', 'Antiem...  
16  ['Antiviral drugs', 'Pain relievers', 'IV flui...  
17  ['Antibiotics', 'Antipyretics', 'Analgesics', ...  
18  ['Vaccination', 'Antiviral drugs', 'IV fluids'...  
19  ['Vaccination', 'Antiviral drugs', 'IV fluids'...  
20  ['Antiviral drugs', 'IV fluids', 'Blood transf...  
21  ['Antiviral drugs', 'IV fluids', 'Blood transf...  
22  ['Antiviral drugs', 'IV fluids', 'Blood transf...  
23  ['Alcohol cessation', 'Corticosteroids', 'IV f...  
24  ['Antibiotics', 'Isoniazid', 'Rifampin', 'Etha...  
25  ['Antipyretics', 'Decongestants', 'Cough suppr...  
26  ['Antibiotics', 'Antiviral drugs', 'Antifungal...  
27  ['Laxatives', 'Pain relievers', 'Warm baths', ...  
28  ['Nitroglycerin', 'Aspirin', 'Beta-blockers', ...  
29  ['Compression stockings', 'Exercise', 'Elevati...  
30  ['Levothyroxine', 'Antithyroid medications', '...  
31  ['Antithyroid medications', 'Radioactive iodin...  
32  ['Glucose tablets', 'Candy or juice', 'Glucago...  
33  ['Pain relievers', 'Exercise', 'Hot and cold p...  
34  ['NSAIDs', 'Disease-modifying antirheumatic dr...  
35  ['Vestibular rehabilitation', 'Canalith reposi...  
36  ['Topical treatments', 'An

In [96]:
diets

Disease  \
0                         Fungal infection   
1                                  Allergy   
2                                     GERD   
3                      Chronic cholestasis   
4                            Drug Reaction   
5                     Peptic ulcer disease   
6                                     AIDS   
7                                 Diabetes   
8                          Gastroenteritis   
9                         Bronchial Asthma   
10                            Hypertension   
11                                Migraine   
12                    Cervical spondylosis   
13            Paralysis (brain hemorrhage)   
14                                Jaundice   
15                                 Malaria   
16                             Chicken pox   
17                                  Dengue   
18                                 Typhoid   
19                             hepatitis A   
20                             Hepatitis B   
21                             Hepatitis C   
22                             Hepatitis D   
23                             Hepatitis E   
24                     Alcoholic hepatitis   
25                            Tuberculosis   
26                             Common Cold   
27                               Pneumonia   
28            Dimorphic hemmorhoids(piles)   
29                            Heart attack   
30                          Varicose veins   
31                          Hypothyroidism   
32                         Hyperthyroidism   
33                            Hypoglycemia   
34                         Osteoarthristis   
35                               Arthritis   
36  (vertigo) Paroymsal Positional Vertigo   
37                                    Acne   
38                 Urinary tract infection   
39                               Psoriasis   
40                                Impetigo   

                                                 Diet  
0   ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...  
1   ['Elimination Diet', 'Omega-3-rich foods', 'Vi...  
2   ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...  
3   ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...  
4   ['Antihistamine Diet', 'Omega-3-rich foods', '...  
5   ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...  
6   ['Balanced Diet', 'Protein-rich foods', 'Fruit...  
7   ['Low-Glycemic Diet', 'Fiber-rich foods', 'Lea...  
8   ['Bland Diet', 'Bananas', 'Rice', 'Applesauce'...  
9   ['Anti-Inflammatory Diet', 'Omega-3-rich foods...  
10  ['DASH Diet', 'Low-sodium foods', 'Fruits and ...  
11  ['Migraine Diet', 'Low-Tyramine Diet', 'Caffei...  
12  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
13  ['Heart-Healthy Diet', 'Low-sodium foods', 'Fr...  
14  ['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits...  
15  ['Malaria Diet', 'Hydration', 'High-Calorie Di...  
16  ['Chicken Pox Diet', 'High-Calorie Diet', 'Sof...  
17  ['Dengue Diet', 'Hydration', 'High-Calorie Die...  
18  ['Typhoid Diet', 'High-Calorie Diet', 'Soft an...  
19  ['Hepatitis A Diet', 'High-Calorie Diet', 'Sof...  
20  ['Hepatitis B Diet', 'High-Calorie Diet', 'Sof...  
21  ['Hepatitis C Diet', 'High-Calorie Diet', 'Sof...  
22  ['Hepatitis D Diet', 'High-Calorie Diet', 'Sof...  
23  ['Hepatitis E Diet', 'High-Calorie Diet', 'Sof...  
24  ['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits...  
25  ['TB Diet', 'High-Calorie Diet', 'Soft and bla...  
26  ['Cold Diet', 'Hydration', 'Warm fluids', 'Res...  
27  ['Pneumonia Diet', 'High-Calorie Diet', 'Soft ...  
28  ['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydra...  
29  ['Heart-Healthy Diet', 'Low-sodium foods', 'Fr...  
30  ['Varicose Veins Diet', 'High-Fiber Diet', 'Fr...  
31  ['Hypothyroidism Diet', 'Iodine-rich foods', '...  
32  ['Hyperthyroidism Diet', 'Low-Iodine Diet', 'C...  
33  ['Hypoglycemia Diet', 'Complex carbohydrates',...  
34  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
35  ['Arthritis Diet', 'Anti-Inflammatory Diet', '...  
36  ['Vertigo Diet', 'Low-Salt

In [97]:
description

Disease  \
0                         Fungal infection   
1                                  Allergy   
2                                     GERD   
3                      Chronic cholestasis   
4                            Drug Reaction   
5                     Peptic ulcer disease   
6                                     AIDS   
7                                 Diabetes   
8                          Gastroenteritis   
9                         Bronchial Asthma   
10                            Hypertension   
11                                Migraine   
12                    Cervical spondylosis   
13            Paralysis (brain hemorrhage)   
14                                Jaundice   
15                                 Malaria   
16                             Chicken pox   
17                                  Dengue   
18                                 Typhoid   
19                             hepatitis A   
20                             Hepatitis B   
21                             Hepatitis C   
22                             Hepatitis D   
23                             Hepatitis E   
24                     Alcoholic hepatitis   
25                            Tuberculosis   
26                             Common Cold   
27                               Pneumonia   
28            Dimorphic hemmorhoids(piles)   
29                            Heart attack   
30                          Varicose veins   
31                          Hypothyroidism   
32                         Hyperthyroidism   
33                            Hypoglycemia   
34                         Osteoarthristis   
35                               Arthritis   
36  (vertigo) Paroymsal Positional Vertigo   
37                                    Acne   
38                 Urinary tract infection   
39                               Psoriasis   
40                                Impetigo   

                                          Description  
0   Fungal infection is a common skin condition ca...  
1   Allergy is an immune system reaction to a subs...  
2   GERD (Gastroesophageal Reflux Disease) is a di...  
3   Chronic cholestasis is a condition where bile ...  
4   Drug Reaction occurs when the body reacts adve...  
5   Peptic ulcer disease involves sores that devel...  
6   AIDS (Acquired Immunodeficiency Syndrome) is a...  
7   Diabetes is a chronic condition that affects h...  
8   Gastroenteritis is an inflammation of the stom...  
9   Bronchial Asthma is a respiratory condition ch...  
10  Hypertension, or high blood pressure, is a com...  
11  Migraine is a type of headache that often invo...  
12  Cervical spondylosis is a degenerative conditi...  
13  Paralysis (brain hemorrhage) refers to the los...  
14  Jaundice is a yellow discoloration of the skin...  
15  Malaria is a mosquito-borne infectious disease...  
16  Chicken pox is a highly contagious viral infec...  
17  Dengue is a mosquito-borne viral infection cau...  
18  Typhoid is a bacterial infection that can lead...  
19              hepatitis A is a viral liver disease.  
20  Hepatitis B is a viral infection that attacks ...  
21  Hepatitis C is a viral infection that causes l...  
22  Hepatitis D is a serious liver disease caused ...  
23  Hepatitis E is a viral infection that causes l...  
24  Alcoholic hepatitis is inflammation of the liv...  
25  Tuberculosis is a bacterial infection that pri...  
26  Common Cold is a viral infection of the upper ...  
27  Pneumonia is an inflammatory condition affecti...  
28  Dimorphic hemmorhoids(piles) is a condition ch...  
29  Heart attack is a sudden and severe reduction ...  
30  Varicose veins are enlarged, twisted veins tha...  
31  Hypothyroidism is a condition where the thyroi...  
32  Hyperthyroidism is a condition where the thyro...  
33  Hypoglycemia is a condition characterized by a...  
34  Osteoarthristis is a degenerative joint diseas...  
35  Arthritis is inflammation of one or more joint...  
36  (Vertigo) Paroxysmal Posit

In [103]:
#Helper Function 

def helper(dis):
    descr = description[description['Disease'] == dis ]['Description']
    descr = " ".join([ w for w in descr])
    
    pre = precaution[precaution['Disease'] == dis ][['Precaution_1',	'Precaution_2',	'Precaution_3'	,'Precaution_4']]
    pre  = [col for col in pre.values]


    diet = diets[diets['Disease']== dis ]['Diet']
    diet = [diet for diet in diet.values]
    
    work = workout[workout['disease']== dis ]['workout']
    work = [work for work in work.values]
    
    med = medication[medication['Disease'] == dis ]['Medication']
    med = [med for med in med.values]

    return descr , pre , diet , med, work


In [104]:
symptom_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}

diseases_dict = {15: 'Fungal infection', 20: 'Hepatitis C', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 21: 'Hepatitis D', 19: 'Hepatitis B', 4: 'Allergy', 40: 'hepatitis A', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 27: 'Impetigo'}




#model prediction 

def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptom_dict))
    for item in patient_symptoms:
        input_vector[symptom_dict[item]] = 1
    return diseases_dict[svc.predict([input_vector])[0]]

In [108]:
symptoms = input('Enter Your Symptoms Here:')
user_symptoms = [ s for s in symptoms.split(',')]
user_symptoms = [ sym.strip("[]") for sym in user_symptoms]

predicted_disease = get_predicted_value(user_symptoms)
descr , pre , diet , med, work = helper(predicted_disease)


#Result Time 
print('********************************Predicted Disease ************************************')
print(" Harsh's Machine Prediction is:-", predicted_disease )
print('********************************Predicted Description ************************************')
print(descr)
print('********************************Predicted Precautions ************************************')
i = 1
for j in pre[0]:
    print(i , ':' , j)
    i += 1
print('********************************Predicted Diets ************************************')
for i in diet:
    
    print(i)
    
print('********************************Predicted Medications ************************************')
i = 1 
for j in med:
    print(i, ":", j)
    i+= 1 
print('********************************Predicted Workouts ************************************')
i = 1 
for j in work:
    print(i, ":", j)
    i+= 1 

Enter Your Symptoms Here: acidity


********************************Predicted Disease ************************************
 Harsh's Machine Prediction is:- Urinary tract infection
********************************Predicted Description ************************************
Urinary tract infection is an infection in any part of the urinary system.
********************************Predicted Precautions ************************************
1 : drink plenty of water
2 : increase vitamin c intake
3 : drink cranberry juice
4 : take probiotics
********************************Predicted Diets ************************************
['UTI Diet', 'Hydration', 'Cranberry juice', 'Probiotics', 'Vitamin C-rich foods']
********************************Predicted Medications ************************************
1 : ['Antibiotics', 'Urinary analgesics', 'Phenazopyridine', 'Antispasmodics', 'Probiotics']
********************************Predicted Workouts ************************************
1 : Stay hydrated
2 : Consume cranberry products
3 : Incl